In [2]:
# ━━━━ SQL 세팅 (코랩 첫 셀에 실행!) ━━━━

# 1. 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

# 2. 필요한 도구 불러오기
import pandas as pd
import sqlite3              # SQLite — 파이썬에 기본 내장!

# 3. 데이터 경로
PATH = '/content/drive/MyDrive/Colab Notebooks/data/'

# 4. 데이터베이스 만들기 (파일 하나로!)
conn = sqlite3.connect('titanic.db')
# sqlite3.connect() = "titanic.db라는 데이터베이스를 만들거나 열어줘"
# conn = connection(연결)의 줄임말

# 5. 타이타닉 CSV를 데이터베이스 테이블로 넣기
df = pd.read_csv(PATH + 'titanic_train.csv')
df.to_sql('passengers', conn, index=False, if_exists='replace')
# 'passengers'라는 이름의 테이블로 저장
# if_exists='replace': 이미 있으면 덮어쓰기

print(f'✅ passengers 테이블 생성 완료! ({len(df)}행)')

Mounted at /content/drive
✅ passengers 테이블 생성 완료! (891행)

In [3]:
# SQL을 실행하고 결과를 예쁘게 보여주는 함수
def sql(query):
    """SQL 쿼리를 실행하고 결과를 DataFrame으로 반환"""
    result = pd.read_sql(query, conn)
    return result

# 사용법: sql("SQL 쿼리")
sql("SELECT * FROM passengers LIMIT 5")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [ ]:
datarian

In [4]:
def sql(query):
    """SQL 쿼리를 실행하고 결과를 DataFrame으로 보여주는 함수"""
    result = pd.read_sql(query, conn)
    return result

# 테스트
sql("SELECT * FROM passengers LIMIT 3")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S

In [5]:
conn.execute("""
CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    price INTEGER,
    category TEXT
)
""")
conn.commit()
print('✅ products 테이블 생성 완료')

✅ products 테이블 생성 완료

In [6]:
# 좀 더 복잡한 예시
conn.execute("""
CREATE TABLE IF NOT EXISTS employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT DEFAULT '미정',
    salary INTEGER,
    hire_date TEXT,
    is_active INTEGER DEFAULT 1
)
""")
conn.commit()
# DEFAULT '미정' = 부서를 안 넣으면 자동으로 '미정'
# DEFAULT 1 = 활성 여부를 안 넣으면 자동으로 1(활성)

NameError: name 'database' is not defined

In [9]:
# 1. 데이터베이스 내의 모든 테이블 목록 확인
print("--- 테이블 목록 ---")
display(sql("SELECT name FROM sqlite_master WHERE type='table'"))

# 2. 특정 테이블(예: passengers)의 구조 확인
print("\n--- passengers 테이블 상위 5개 행 ---")
display(sql("SELECT * FROM passengers LIMIT 5"))

--- 테이블 목록 ---

         name
0  passengers
1    products
2   employees

--- passengers 테이블 상위 5개 행 ---

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [10]:
sql("SELECT * FROM passengers LIMIT 5")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [11]:
sql("SELECT DISTINCT Embarked FROM passengers")

  Embarked
0        S
1        C
2        Q
3     None

In [12]:
sql("""
SELECT
    Name AS 이름,
    Sex AS 성별,
    Age AS 나이,
    Survived AS 생존여부
FROM passengers
LIMIT 5
""")

                                                  이름      성별    나이  생존여부
0                            Braund, Mr. Owen Harris    male  22.0     0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0     1
2                             Heikkinen, Miss. Laina  female  26.0     1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0     1
4                           Allen, Mr. William Henry    male  35.0     0

In [13]:
sql("SELECT COUNT(*) AS 총승객수 FROM passengers")

   총승객수
0   891

In [14]:
sql("SELECT Name, Age FROM passengers WHERE Age >= 30 LIMIT 5")      # 30세 이상
sql("SELECT Name, Fare FROM passengers WHERE Fare >= 100 LIMIT 5")   # 요금 100 이상
sql("SELECT Name, Pclass FROM passengers WHERE Pclass = 1 LIMIT 5")  # 1등석

                                                Name  Pclass
0  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
2                            McCarthy, Mr. Timothy J       1
3                           Bonnell, Miss. Elizabeth       1
4                       Sloper, Mr. William Thompson       1

In [15]:
sql("SELECT Name, Age FROM passengers WHERE Age >= 30 LIMIT 5")

                                                Name   Age
0  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
2                           Allen, Mr. William Henry  35.0
3                            McCarthy, Mr. Timothy J  54.0
4                           Bonnell, Miss. Elizabeth  58.0

In [16]:
sql("SELECT Name, Pclass FROM passengers WHERE Pclass = 1 LIMIT 5")

                                                Name  Pclass
0  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
2                            McCarthy, Mr. Timothy J       1
3                           Bonnell, Miss. Elizabeth       1
4                       Sloper, Mr. William Thompson       1